openapi: '3.0.2'
info:
  title: participantActivityHistory
  version: '1.0.0'
servers:
  - url: https://api.server.test/v1
paths:
  /participantActivityHistory:
    get:
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::Account}:function:lambdaapicall/invocations
        httpMethod: POST
      parameters:
        - name: ssn
          in: query
          required: true
          schema:
            type: string
            default: abc
          description: ssn of participant  
        - name: pon
          in: query
          required: true
          schema:
            type: string
            default: abc
          description: PO number of participant  
        - name: start_date
          in: query
          required: true
          schema:
            type: string
            default: 2022-05-04
          description: Start Date
        - name: end_date
          in: query
          required: true
          schema:
            type: string
            default: 2022-06-05
          description: End Date         
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: "empty schema"                                                                             